### ISSUE TITLE
1.18.1 Regions Issue - Boss Settings Reset Themselves on Reboot/Plugin Reload

### ISSUE THREAD

**Issue by celticpixie14** [kangarko/Boss#1009]
Minecraft Version : 1.18.1
Boss Version: 4.3.2
Paper - 214 (MC:1.18.1)

Issue: When creating regions for bosses to spawn - have no issue doing so - setting up locations, spawn rules etc. Locations and regions created are still there, however, whenever I reload the boss plugin - the settings go back to nil. i.e. - spawn rules, locations and regions are set to none/disabled etc. Same thing happens on server reboots after resetting the information again. Tried reverting back a version to 4.3.1 - did not work. No errors in console. I have attached images to show the above, down below. Also boss mobs are spawning in with Steve heads, this occurs on versions 4.3.1 and 4.3.2. 

![image](https://user-images.githubusercontent.com/88334347/158063479-0ba336d4-db01-4654-930d-aa79142ef24a.png)

![image](https://user-images.githubusercontent.com/88334347/158063491-b47ecc02-9448-4c2e-91d7-a6ee22ee53dc.png)

![image](https://user-images.githubusercontent.com/88334347/158063496-a9826bec-f1ea-4e1d-b5f4-132ea210a991.png)

![image](https://user-images.githubusercontent.com/88334347/158063499-42d3563c-c32a-4b57-9607-63c7c818b8a0.png)

![image](https://user-images.githubusercontent.com/88334347/158063505-f17b9b52-4983-420c-8e20-d1bf06d8ffec.png)

**Comment by kangarko** [comment]
Should be patched in the next release, let me know if you still will have issues below and I am a happy to help (so sorry for the delay this time)

**Comment by celticpixie14** [comment]
Hi Kangarko,

Thanks for the update/response - just to let you know, after updating the plugin, we are still having the same issues with regions. Alongside, our boss menu and completely changed server side. We are now, seemingly missing the bosses we had before. They still exist in the files but not in /boss menu. The bosses also still have steve heads. Attached images below, the first one shows what is available via /boss menu - the second one shows the amount of bosses we actually have in the bosses file. The /boss butcher command does not work as the menu is showing the file bosses as not existing. The update has essentially removed the bosses from the server - even though they remain in the files. Same with the regions, they still exist in files but not on the server. 

![image](https://user-images.githubusercontent.com/88334347/159568635-bfa808b5-6b16-4d9e-b37f-33a4b51ffd3c.png)

![image](https://user-images.githubusercontent.com/88334347/159568656-111282f6-af98-4f6e-aaa4-649b56717607.png)

**Comment by celticpixie14** [comment]
This error message appears in the error.log consistently. Its the same boss "arthur" - that boss appears at the start of the list, so I wonder if its starting there, failing to load, and won't get any further than that. Debug zip file attached below. Thankyou 


------------------------------------[ 27.03.2022 09:01:38 ]-----------------------------------
Boss 4.3.3 encountered an InvocationTargetException
Running Paper 1.18.2-R0.1-SNAPSHOT and Java 17.0.1
Plugins: LoginRewards v1.0, Chunky v1.2.164, PlaceholderAPI v2.11.1, DeluxeCommands v1.12-DEV, GeyserSkinManager v1.6, CommandToItem v${version}, PyroLib v1.0.2, DeluxeTags v1.8.2-Release, VillagerModifications v1.5.0, MC-Cron v1.9.1, DeathMessages v1.0, ViaVersion v4.2.2-SNAPSHOT, NBTAPI v2.9.2, ViaBackwards v4.2.1, LuckPerms v5.4.14, GBooster v1.4.2, VoidGen v2.2.1, AnimatedScoreboard v0.2.5, SirBlobmanCore v2.3.5, spark v1.8.0, JetsAntiAFKPro v3.5.1, BuycraftX v12.0.8, Votifier v2.7.3, ProtocolLib v5.0.0-SNAPSHOT-b551, AdvancedPortals v0.8.0, SayWelcome v1.1.1, Vault v1.7.3-b131, floodgate v2.1.0-SNAPSHOT, TokenManager v3.2.6, ViaRewind v2.0.3-SNAPSHOT, ClientDetector v2.4.9, EpicRename v3.10.2, MoneyPouch v3.6.1, Item2Chat v6.6.2, VoteParty v2.32-DEV, PlayerVaults v4.2.5, boosCooldowns v3.17.2, WorldEdit v7.2.10+1742f98, VentureChat v3.3.2, Essentials v2.20.0-dev+1-31732ce, PyroMining v4.3.7, HeadDatabase v4.16.0, Multiverse-Core v4.3.1-b861, AsyncWorldEdit v3.9.4, ajLeaderboards v2.3.0, DeluxeMenus v1.13.5-DEV-null, AuctionGUIPlus v1.22.0, Lottery v1.4.1, WorldGuard v7.0.7+216b061, EssentialsSpawn v2.20.0-dev+1-31732ce, CoreProtect v21.2, ShopGUIPlus v1.72.0, WGEF-Reborn v2.4-stable+035799b, TempFly v3.1.2, AreaShop v2.6.3#CUSTOM, Guilds v3.5.6.3, DecentHolograms v2.3.1, PyroFishingPro v4.6.6, ServerTutorialPlus v1.23.3, Citizens v2.0.29-SNAPSHOT (build 2509), mcMMO v2.1.211, ItemJoin v5.2.4-SNAPSHOT-b810, GriefPrevention v16.18, CrazyCrates v1.10.3, ChestShop v3.12.1-SNAPSHOT (build 345), Elevators v4.0.7, CrazyEnvoy v1.3.13-SNAPSHOT, Boss v4.3.3, NametagEdit v4.5.5, Spartan vBuild 454.1, ClaimFly v1.2.6, Quests v4.2.3-b307, GriefpreventionAddon v0.1-SNAPSHOT, BanFromClaim v1.6.2, CoreArena v3.1.6, Wild v4.4.5-SNAPSHOT, PremiumVanish v2.7.13, AdvancedEnchantments v8.9.7, CMILib v1.1.2.4, MorphRedeem v1.2.3, ProCosmetics v13.2, MobFarmManager v2.0.2.2, CombatLogX v11.0.0.0-Beta-735, BungeeTabListPlus v3.4.4
----------------------------------------------------------------------------------------------

More Information: 
Failed to load boss arthur from bosses
InvocationTargetException (Unknown cause)
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:202)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:160)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:146)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:108)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2210)
	 at Boss-4.3.3.jar//org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
NullPointerException obj is marked non-null but is null
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.SerializeUtil.deserializeItemStack(SerializeUtil.java:685)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.loadDrops(Boss.java:404)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.onLoad(Boss.java:362)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1147)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.<init>(Boss.java:316)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.<init>(Boss.java:301)
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:202)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:160)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:146)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:108)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2210)
	 at Boss-4.3.3.jar//org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
----------------------------------------------------------------------------------------------
[debug.zip](https://github.com/kangarko/Boss/files/8357417/debug.zip)

**Comment by celticpixie14** [comment]
It was 1.18.1 when originally opened the thread, but you'll see in the error log we're now running 1.18.2 - which it also occurs on. Paper Version: 1.18.2 Release 267 (previously 265 - also occurred on this version)

**Comment by kangarko** [comment]
Thanks, will fix. You need to remove that boss completely for now.

**Comment by celticpixie14** [comment]
Thanks for the update Kangarko :)

Regions are now working well, bosses are back and spawning the way they should be. Only two minor issues remain - 1) Steve heads are still there. 2) Even with region keeping set to true, the bosses are still able to leave/wander outside.

**Comment by kangarko** [comment]
1) For skin issues it should be outside of our scope, you can install a plugin such as SkinsRestorer or use online mode instead.
2) Region keeping only teleports bosses back to their region, it does not physically prevent them from navigating to a point outside of it, but once they cross the region's boundary we teleport them back quickly.

**Comment by celticpixie14** [comment]
Alright no worries thanks re; the skin issue.

The only thing is the bosses are not teleporting back at all - had one follow me at least 100 blocks outside a region and wasn't teleported back.

**Comment by kangarko** [comment]
Sorry for the delay, I am busy with other projects right now however I believe this should be resolved in the next release.

**Comment by celticpixie14** [comment]
Brilliant! Thank you so much :)

**Comment by kangarko** [comment]
You do have some plugins that can remove our Boss tag and thus make our plugin no longer register these bosses - Chunky or MobFarmManager or others - next time you see this, please right click the mob - does the chat say that this is a valid boss like this?

![a](https://i.imgur.com/ZvzhBPw.png)

**Comment by celticpixie14** [comment]
Sorry for the delayed response, I hadn't realised you'd responded and hadn't checked notifs. The bosses are still not keeping to regions and as per above - they do appear like that.

![image](https://user-images.githubusercontent.com/88334347/171042121-a1a558ef-d1ab-4e52-bf25-f215f3558fa2.png)

**Comment by kangarko** [comment]
I am sorry, I am traveling on holidays until June 21st, won't be having time to look into this unfortunately. Please if you can, remind me this later and then include your latest /boss zip file so that I can test it. Let me know what exact Boss has that issue.  Until then, just double check that both Region Keeping is enabled and the return spawn location is set: https://i.imgur.com/oSIfIIq.png (But I assume you have it)

**Comment by celticpixie14** [comment]
Not a problem Kangarko, thankyou as always. I will certainly let you know. Enjoy your holidays!

**Comment by celticpixie14** [comment]
Created a test region with a new boss, double checked region keeping and return spawn location were enabled and still had the same issue, attached the zip file here. No rush to check. Just thought I'd leave it here in advance.
[TestBoss.zip](https://github.com/kangarko/Boss/files/8840208/TestBoss.zip)
