### ISSUE TITLE
1.16.3 - Spawn broadcast command does nothing when spawned by both an egg and/or a command.

### ISSUE THREAD

**Issue by RoboKast** [kangarko/Boss#695]
When I try to spawn my boss, both through the egg or the command, the broadcast command does not run. Nothing is mentioned in the console and nothing shows up in-game. I added the broadcast command through the GUI and it still does not occur. 

Here is my config spawning section:

Spawn:
  Commands:
  - Command: broadcast &c&l[BOSS BATTLE] &eGerard The Great &fhas spawned at &e/warp
      arena.&f Challenge him and see if you can win. &cPVP IS ENABLED.
    Chance: 1.0
Spawning:
  Worlds:
    PVP: 50%
  Biomes: {}
  Conditions:
    Time: 0 - 24000
    Light: 0 - 15
    Height: 0 - 256
    Rain: false
    Thunder: false
    Spawn_Under_Water: false

I am a bit confused as to why it generated both a "spawning" and "spawn" section as well.

Thanks.

**Comment by kangarko** [comment]
Did you put that into your yml file manually? If yes, use the GUI to create the command.

**Comment by kangarko** [comment]
And before that, remove that Spawn section completely.

**Comment by RoboKast** [comment]
I removed the section and re-added the commands through the GUI and it still does not notify players.

**Comment by kangarko** [comment]
Please ZIP me your Boss .yml file

**Comment by Reach06** [comment]
i have same problems

**Comment by Reach06** [comment]
pls asap THX

**Comment by kangarko** [comment]
Closing due to inactivity, not a single one of you has bothered to provide your ZIP, I cannot help. If you need help, upload it here below.

**Comment by Reach06** [comment]
here is my zip

Matej Pacan <notifications@github.com> 于2020年11月10日周二 上午2:46写道：

**Comment by Reach06** [comment]
please use gmail to download it

**Comment by kangarko** [comment]
I cannot download it like that, please use uploadfiles.io to submit.

@Reach06 you also did not mention what problem EXACTLY you have, please mention it else I am not able to help

**Comment by Reach06** [comment]
@Matej Pacan here u are https://ufile.io/90ofbz8l
first i need u to forgive me that my english is that bad
my questions is the boss spawning command at gui is not working and piglin
zombie will stuck 'on' the air while i am using them to the mobs




Matej Pacan <notifications@github.com> 于2020年11月12日周四 下午5:59写道：

**Comment by RoboKast** [comment]
Here is my config for one of my bosses. None of the boss commands work for any of the bosses that I have created, however.

https://ufile.io/hnvpg9cy

**Comment by Reach06** [comment]
what server version are you using? i am using 1.16.3 paper
anything i did wrong?

RoboKast <notifications@github.com> 于2020年11月14日周六 上午6:29写道：

**Comment by Reach06** [comment]
[image: 2020-11-16_20.47.57.png]
@kangarko/Boss
<reply@reply.github.com> this is
from ur plugins bosstm ur mobs is floating i didnt do anything console also
show no error


黄伟伦 <wailoon1211@gmail.com> 于2020年11月14日周六 上午6:53写道：

**Comment by Reach06** [comment]
![2020-11-16_20 47 57](https://user-images.githubusercontent.com/74001999/99255190-85115d80-284e-11eb-9636-915079734bd9.png)

**Comment by Reach06** [comment]
[error.log](https://github.com/kangarko/Boss/files/5546342/error.log)
here is my all error.log

**Comment by kangarko** [comment]
Use Boss 3.9.2 and repaste me that error when that happens again

**Comment by Reach06** [comment]
i using 3.9.2 ofcoz


Matej Pacan <notifications@github.com> 于2020年11月17日周二 上午1:17写道：

**Comment by Reach06** [comment]
by the way i also using ur boss config that u gave me boss spawn command
also can't use

黄伟伦 <wailoon1211@gmail.com> 于2020年11月17日周二 上午1:49写道：

**Comment by aerulion** [comment]
Hello, i'm having the same problem. The death commands will be executed, but i can't get the spawn commands to work.

Here is the config i'm using:
https://ufile.io/bmunwg7c

Using Boss v3.9.2 & Paper 1.16.3

**Comment by kangarko** [comment]
@RoboKast and @aerulion  just tested your files with the latest fixes and they work :)
![Uploading Screenshot 2020-11-20 at 08.56.33.pn
<img width="790" alt="Screenshot 2020-11-20 at 08 53 49" src="https://user-images.githubusercontent.com/1918426/99774609-51fcf180-2b0e-11eb-80c2-8ab3d59af514.png">
g…]()


@Reach06 I fixed the error, apologies for the delay

**Comment by Reach06** [comment]
so where can i get the fixed file?

**Comment by kangarko** [comment]
Will release new Boss version tonight, you can use your old files.

**Comment by Reach06** [comment]
@kangarko the boss spawn command still not working
but it wont freeze anymore

**Comment by Reach06** [comment]
![image](https://user-images.githubusercontent.com/74001999/99869531-a8e5f200-2c06-11eb-83a0-0c63b8e3d836.png)

**Comment by Reach06** [comment]
https://ufile.io/tnqdo5xy
this is my boss 'test'

**Comment by aerulion** [comment]
Can confirm, the issue still exists. As stated previously the "on Death" commands are working perfectly fine, but the commands which will be executed once the boss spawns aren't working for me.

**Comment by Reach06** [comment]
There is another question why the amount of material I put on the boss will change itself
then console and error.log show no error

**Comment by Reach06** [comment]
are thoes error is normal?
https://ufile.io/sbj0g5r5

**Comment by Reach06** [comment]
![2020-11-23_08 50 29](https://user-images.githubusercontent.com/74001999/99922057-46593700-2d69-11eb-8d7c-1964421da57d.png)
https://ufile.io/kepxy3if

**Comment by Reach06** [comment]
this boss are set with 150hp
then at in game only have 50hp

**Comment by Reach06** [comment]
1.16.3 is not friendly for me ....

**Comment by kangarko** [comment]
Sorry about the delay, I am investigating this again

**Comment by kangarko** [comment]
Alright I fixed that, apology for the delays:

![a](https://i.imgur.com/ldX4wVv.png)

Boss has 150HP, if you still have that problem then check your spigot.yml file in root server folder for maxHealth or try disabling other plugins.
